openapi: 3.0.0
info:
  title: Linr API
  version: 1.0.2
servers:
  - url: https://1515cada-513e-41f1-9019-beddd771d99d.mock.pstmn.io
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Snippets
  - name: Comments
  - name: Saved
  - name: User
paths:
  /snippets:
    get:
      tags:
        - Snippets
      summary: all  snippets data
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "598"
            Etag:
              schema:
                type: string
                example: '"1987596677"'
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:49:47 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: Data retrieved successfully
                date: "2021-09-15T21:20:24.049Z"
                data:
                  - snippet_id: pMQwEbmozl
                    title: Capitalize String
                    descb: Capitalized first char at string.
                    snippet: >-
                      const capitalize = str => str.charAt(0).toUpperCase() +
                      str.slice(1)
                    username: enjinerd
                    category_det:
                      - id: 2
                        name: cheatseet
                    created_at: 2021-11-12T09:11:27+0000
                    updated: 2021-11-12T09:11:27+0000
                  - snippet_id: _i89Fu_XzJ
                    title: Get URI Parameter
                    descb: Get URI parameter from url.
                    snippet: >-
                      const getURIParameters = url =>
                      (url.match(/([^?=&]+)(=([^&]*))/g) || []).reduce(    (a,
                      v) => (      (a[v.slice(0, v.indexOf('='))] =
                      v.slice(v.indexOf('=') + 1)), a    ),    {}  );
                    username: bisita
                    category_det:
                      - id: 2
                        name: cheatseet
                    created_at: 2021-11-12T09:11:27+0000
                    updated: 2021-11-12T09:11:27+0000
                  - snippet_id: DL3M9bZEyn
                    title: String Reverse
                    descb: Reverse string from behind.
                    snippet: >-
                      const stringReverse = str =>
                      str.split('').reverse().join('');
                    username: denida
                    category_det:
                      - id: 2
                        name: cheatseet
                    created_at: 2021-11-12T09:11:27+0000
                    updated: 2021-11-12T09:11:27+0000
    post:
      tags:
        - Snippets
      summary: add snippet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                snippet_id: 1EUYFo2z5u
                title: Remove duplicates array values
                descb: Remove duplicates array values.
                snippet: const removeDuplicates = arr => [...new Set(arr)];
                username: egian
                category_det:
                  - id: 2
                    name: cheatseet
                created_at: 2021-11-12T09:11:27+0000
                updated: 2021-11-12T09:11:27+0000
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "202"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:06 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: created
                message: A new snippet data created.
                date: "2021-09-15T15:42:28.988Z"
                data:
                  snippet_id: 1EUYFo2z5u
                  title: Remove duplicates array values
                  descb: Remove duplicates array values.
                  snippet: const removeDuplicates = arr => [...new Set(arr)];
                  username: egian
                  category_det:
                    - id: 2
                      name: cheatseet
                  created_at: 2021-11-12T09:11:27+0000
                  updated: 2021-11-12T09:11:27+0000
  /snippets/{snippet_id}:
    delete:
      tags:
        - Snippets
      summary: remove  a snippet
      security:
        - bearerAuth: []
      parameters:
        - name: snippet_id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "206"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:37 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: deleted
                message: A data has been deleted
                date: "2021-09-15T17:18:54.086Z"
                deletedData:
                  snippet_id: pMQwEbmozl
                  title: Capitalize String
                  username: enjinerd
    put:
      tags:
        - Snippets
      summary: Update a snippet
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                descb: Changed describe
      security:
        - bearerAuth: []
      parameters:
        - name: snippet_id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "207"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:21 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: updated
                message: A data has been updated
                date: "2021-09-15T17:38:28.597Z"
                data:
                  snippet_id: pMQwEbmozl
                  title: Capitalize String
                  descb: Changed descriobe
  /comments/{snippet_id}:
    get:
      tags:
        - Comments
      summary: comments from spesifc snippets
      parameters:
        - name: snippet_id
          in: path
          schema:
            type: string
          required: true
          example: pMQwEbmozl
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "598"
            Etag:
              schema:
                type: string
                example: '"1987596677"'
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:49:47 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: Data retrieved successfully
                date: "2021-09-15T21:20:24.049Z"
                data:
                  snippet_id: pMQwEbmozl
                  title: Capitalize String
                  comments:
                    - comment_id: QiLzXJRkPh
                      comment: nice
                      username: reka
                      created_at: 2021-11-12T09:11:27+0000
                      updated: 2021-11-12T09:11:27+0000
                    - comment_id: M1kpqr2boQ
                      comment: awesome
                      username: isal
                      created_at: 2021-11-12T09:11:27+0000
                      updated: 2021-11-12T09:11:27+0000
  /comments/{comment_id}:
    delete:
      tags:
        - Comments
      summary: delete a comment
      security:
        - bearerAuth: []
      parameters:
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
          example: pMQwEbmozl
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "206"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:37 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: deleted
                message: A data has been deleted
                date: "2021-09-15T17:18:54.086Z"
                deletedData:
                  comment_id: QiLzXJRkPh
                  comment: nice
                  username: reka
    put:
      tags:
        - Comments
      summary: Update a comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                comment: Changed comment
      security:
        - bearerAuth: []
      parameters:
        - name: comment_id
          in: path
          schema:
            type: string
          required: true
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "207"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:21 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: updated
                message: A data has been updated
                date: "2021-09-15T17:38:28.597Z"
                data:
                  comment_id: M1kpqr2boQ
                  comment: It's help me
                  username: isal
  /comments:
    post:
      tags:
        - Comments
      summary: add comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                comment_id: O8bcxATi7b
                comment: Wow, its rocks
                snippet_id: pMQwEbmozl
                username: veraanb
                created_at: 2021-11-12T09:11:27+0000
                updated: 2021-11-12T09:11:27+0000
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "202"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:06 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: created
                message: A new comment created.
                date: "2021-09-15T15:42:28.988Z"
                data:
                  comment_id: O8bcxATi7b
                  comment: Wow, its rocks
                  snippet_id: pMQwEbmozl
                  username: veraanb
                  created_at: 2021-11-12T09:11:27+0000
                  updated: 2021-11-12T09:11:27+0000
  /saved:
    get:
      tags:
        - Saved
      summary: all saved
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "598"
            Etag:
              schema:
                type: string
                example: '"1987596677"'
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:49:47 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: Data retrieved successfully
                date: "2021-09-15T21:20:24.049Z"
                data:
                  - snippet_id: 1VadYg2T8_a
                    title: Random Sorting
                  - snippet_id: asyTge6_1j
                    title: Generate UUID
                  - snippet_id: pMQwEbmozl
                    title: Capitalize String
                  - snippet_id: DL3M9bZEyn
                    title: String Reverse
                  - snippet_id: _i89Fu_XzJ
                    title: Get URI Parameter
                  - snippet_id: 1EUYFo2z5u
                    title: Remove duplicates array values
    delete:
      tags:
        - Saved
      summary: delete a saved snippet
      security:
        - bearerAuth: []
      parameters:
        - name: saved_id
          in: query
          schema:
            type: string
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "206"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:37 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: deleted
                message: A data has been deleted
                date: "2021-09-15T17:18:54.086Z"
                username: reka
                deletedData:
                  snippet_id: _i89Fu_XzJ
                  title: Get URI Parameter
    post:
      tags:
        - Saved
      summary: add a saved
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                comment_id: O8bcxATi7b
                comment: Wow, its rocks
                snippet_id: pMQwEbmozl
                username: veraanb
                created_at: 2021-11-12T09:11:27+0000
                updated: 2021-11-12T09:11:27+0000
      security:
        - bearerAuth: []
      responses:
        "201":
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "202"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:06 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: created
                message: A new saved created.
                date: "2021-09-15T15:42:28.988Z"
                data:
                  snippet_id: pMQwEbmozl
                  title: Capitalize String
  /user:
    get:
      tags:
        - User
      summary: get a user info
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "598"
            Etag:
              schema:
                type: string
                example: '"1987596677"'
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:49:47 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 200
                status: success
                message: Data retrieved successfully
                date: "2021-09-15T21:20:24.049Z"
                data:
                  code: 200
                  status: success
                  message: Data retrieved successfully
                  date: "2021-09-15T21:20:24.049Z"
                  data:
                    user_id: LMcj6nX7vh
                    username: reka
                    email: reka@email.dev
                    created_at: 2021-11-12T09:11:27+0000
                    updated: 2021-11-12T09:11:27+0000
    put:
      tags:
        - User
      summary: Update a username
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: newreka
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: Cowboy
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Powered-By:
              schema:
                type: string
                example: Express
            Access-Control-Allow-Origin:
              schema:
                type: string
                example: "*"
            Access-Control-Allow-Methods:
              schema:
                type: string
                example: GET,PUT,POST,DELETE,OPTIONS
            Access-Control-Allow-Headers:
              schema:
                type: string
                example: X-Requested-With,Content-Type,Cache-Control,access_token
            Content-Type:
              schema:
                type: string
                example: application/json
            Content-Length:
              schema:
                type: integer
                example: "207"
            Vary:
              schema:
                type: string
                example: Accept-Encoding
            Date:
              schema:
                type: string
                example: Thu, 16 Sep 2021 00:50:21 GMT
            Via:
              schema:
                type: number
                example: 1.1 vegur
          content:
            application/json:
              schema:
                type: object
              example:
                code: 201
                status: updated
                message: A data has been updated
                date: "2021-09-15T17:38:28.597Z"
                data:
                  code: 200
                  status: success
                  message: Data retrieved successfully
                  date: "2021-09-15T21:20:24.049Z"
                  data:
                    user_id: LMcj6nX7vh
                    username: newreka
